### ISSUE TITLE
CDN endpiont?

### ISSUE THREAD

**Issue by joshOfAllTrades** [hexpm/specifications#15]
The readme says, "To host a repository only the CDN endpoint has to be implemented." I don't see anything called the CDN endpoint in the documentation.

**Comment by ericmj** [comment]
It should be the "Repository endpoint".

**Comment by ericmj** [comment]
Thanks for catching this.

**Comment by joshOfAllTrades** [comment]
You're welcome. Are there any instructions on how to install/run hex on a private server? Does it require modification to do so?

**Comment by ericmj** [comment]
There are no more instructions than what is in this repository. It depends on your requirements and what you need also.
