### ISSUE TITLE
The Registry specification seems out of date.

### ISSUE THREAD

**Issue by djnym** [hexpm/specifications#9]
There appears to be another special key '$$installs2$$' which probably needs documentation as it's unclear how to interpret it.

**Comment by ericmj** [comment]
You only need to interpret the keys documented in the specification. We should probably add a note that there may be keys in the ETS table that are not specified in the spec.

**Comment by djnym** [comment]
If I end up implementing my own registry table for a private repo will it work with normal clients if that key does not exist?  I guess I would question any undocumented keys at all if you expect others to build registries, as there is no guarantee that any client would be able to use a registry I put together, right?

**Comment by ericmj** [comment]
It is supposed to work in all clients. If it does not it's a bug in the client, I will check that the Mix client works correctly when that key is missing.

**Comment by ericmj** [comment]
The client handles this correctly, but you won't get update notifications. With the new registry format we will move installs to another place so you don't have to worry about implementing this.
